### ISSUE TITLE
CForms II is not i

### ISSUE THREAD

**Issue by morenofede** [bgermann/cforms2#10]
Hi Gents!
   I just installed the new version of Wordpress 4.3 and the last version of the Cforms II 14.9.12 and it seems that is nos possible to access through Cforms panel, because of a lack of a Cform icon in the WP dashboard.
Cform is a great tool! and I wonder to use it in this new WP version. Any idea which could be the problem?
Attached are some pictures of my screen. Kind regards. Federico

![screen shot 2015-08-28 at 22 38 25](https://cloud.githubusercontent.com/assets/14024340/9559950/903feb80-4dd5-11e5-94a4-ef7a4f9f53ad.png)
![screen shot 2015-08-28 at 22 38 05](https://cloud.githubusercontent.com/assets/14024340/9559951/90439a14-4dd5-11e5-934a-978492ee7b53.png)

**Comment by bgermann** [comment]
Please try to disable all plugins. Then enable cformsII and check if the button is available. Enable one plugin after the other and check agin. If you enable one and the button is hidden as a side effect, post the plugin's name here and I will check it.

**Comment by morenofede** [comment]
Many Thannks Bgermann, it works!
I had installed these plugins: WP Maintenance mode, UpdraftPlus - Backup/Restore, IzeeChat and Cforms2

Good weekend!
Federico
