### ISSUE TITLE
Problem uploading files

### ISSUE THREAD

**Issue by ntassani** [bgermann/cforms2#11]
Hi! I have the absolute url ok with 777 permissions: /home/horasext/public_html/articulos/wp-content/plugins/cforms2/adjuntos
I added the extensions: jpg, jpeg, png, cdr, pdf, ai
Also i try with the point in the extensions. eg: .jpg, .jpeg, etc.

But i get error in the filetype.
Any help? Thanks for revive forms :)

**Comment by bgermann** [comment]
That is very odd. The version without the dots should be ok. What error exactly do you get?

**Comment by bgermann** [comment]
closing as not active anymore
