### ISSUE TITLE
Is it in the roadmap to make the multi-step forms asynchronous?

### ISSUE THREAD

**Issue by jesusiniesta** [bgermann/cforms2#14]
Right now Ajax is disabled for multi-part/multi-page forms, and would be great to do that transition through JS and saving each individual form asynchronously

**Comment by bgermann** [comment]
I started to rewrite some of the multipart form handling to get rid of session cookies. I will check, if it is possible to have AJAX support for them as well in this process.

**Comment by jesusiniesta** [comment]
Let me know if I can collaborate there :)

**Comment by bgermann** [comment]
I will not work on this feature request. Cannot afford the time. But if someone wants to submit patches, I am happy to take them.
