### ISSUE TITLE
CSV download

### ISSUE THREAD

**Issue by mibanescu** [bgermann/cforms2#15]
It looks like the ability to download records has been removed in 14.13 by commit https://github.com/bgermann/cforms2/commit/6db65708cd85a281b89c16ca720c047b3d1cb46a - that feature was really useful to us.

Is there any alternate way to download the records in a spreadsheet?

Thank you for all your work on this wonderful plugin!

**Comment by bgermann** [comment]
There are other ways: You can export directly via SQL or use the CFDB plugin as a tracking DB replacement, which is the preferred way to save form submissions. The tracking DB will be removed for new installations in the next version and will be removed in a future version. You can checkout master branch, if you want to export your existing data to CFDB.

**Comment by mibanescu** [comment]
Thank  you!

I have tried to figure out how to make cformsII use CFDB, but so far I came up short. CFDB doesn't see my existing cformsII data. After trying unsuccessfully to figure something out, I gave up.

Do you have any docs on how this integration is going to work?

**Comment by bgermann** [comment]
If you are on cformsII GitHub master trunk, you will have an export link available on the Tracking DB page. Be sure to have cforms enabled as a target in CFDB.
