### ISSUE TITLE
my_cforms_filter implementing in 14.14 

### ISSUE THREAD

**Issue by abramovku** [bgermann/cforms2#18]
Hi 
I used my_cforms_filter() for filtering fields after submitting form and validation. 
In readme.txt I find that old functions `my_cforms_filter` is deprecated.
Is there a similar algorithm in the new version?

**Comment by bgermann** [comment]
Check out cforms2_after_processing_action. If you need to filter something before standard processing, please let me know what exactly you need to filter. Maybe I will integrate a new filter in version 15.0. Up to now it is perfectly fine to use 14.13.3.

**Comment by abramovku** [comment]
`cforms2_after_processing_action`  doesn't contain the hidden fields which we have added using jquery, so we need action before processing after validation. 
We use cforms as form builder for eccomerce plugin and we need dynamic fields to pass shop parameters for example the price of the goods etc.

last implementation:
```
function my_cforms_filter($POSTdata) {
  if (is_array($POSTdata)){
     if ($POSTdata['wpshop']==1){
      $cform_name = Wpshop_RecycleBin::getCformsName($POSTdata);
	  //echo "<script>console.log( 'Debug Objects: " . json_encode($POSTdata) . "' );</script>";
      if (!empty($cform_name)) {
        Wpshop_Forms::setDataSend();
        return Wpshop_RecycleBin::actionOrder($POSTdata);
      }
       return $POSTdata; 
    }
  }
}
```

**Comment by abramovku** [comment]
`$POSTdata['wpshop']==1 ` was a hidden field, in this way we understood that this form for eccomerce plugin

**Comment by bgermann** [comment]
If you do not manipulate $POSTdata in your functions, something like this should work:

```
add_action('cforms2_after_processing_action', function ($validFormData) {
  $POSTdata = $validFormData['data'];
  if (is_array($POSTdata)){
     if ($POSTdata['wpshop']==1){
      $cform_name = Wpshop_RecycleBin::getCformsName($POSTdata);
      if (!empty($cform_name)) {
        Wpshop_Forms::setDataSend();
        Wpshop_RecycleBin::actionOrder($POSTdata);
      }
    }
  }
}
```

**Comment by abramovku** [comment]
In $validFormData['data'] where is no field `wpshop =1` although the form field exist

**Comment by abramovku** [comment]
Cforms passes only fields from cforms constructor

**Comment by abramovku** [comment]
I need to be able to add my own fields, bypassing the cforms

**Comment by bgermann** [comment]
Okay. You can use the "parse_request" action or the "request" filter. Actually you can use any WordPress action or filter and manipulate the $_POST superglobal directly.
