### ISSUE TITLE
CSS/JS not loading correctly on admin pages.

### ISSUE THREAD

**Issue by 0x539** [bgermann/cforms2#4]
Hey

When you go to the admin area in the backend, once you do an action like removing a field or viewing a different form the js/css disappears and the page renders as follows:

http://imgur.com/5CUnIYV

From what I can tell its something to do with the page slug. In the url bar I am seeing: 

/admin.php?page=cforms2%2Fcforms-options.php

When I load the page there is a split second where the url is:

/admin.php?page=cforms2/cforms-options.php

and the page loads fine. Then if you click in the url bar and press enter, or refresh the css/js disappears.

I have tested in latest chrome and firefox and IE11 all do the same thing. I did look at the code but it goes above my head.

I also tested locally (XAMPP)(as per screenshot) and on my development server both with the same outcome.

**Comment by 0x539** [comment]
Little bit more info:

Local wordpress install is fully up to date (4.2.1), using the twentyfifteen theme with no other plugins installed.

**Comment by bgermann** [comment]
I am already aware of this as it is the same error as in https://wordpress.org/support/plugin/cforms2

**Comment by bgermann** [comment]
I will fix it asap.

**Comment by 0x539** [comment]
Ahh sorry I should have checked :(
