### ISSUE TITLE
Corrupted cforms settings array (raw code)

### ISSUE THREAD

**Issue by jasperf** [bgermann/cforms2#9]
Just cloned a site from .com to .dev and now I see Corrupted cforms settings array (raw code) with the option to fix the array data. See https://gist.github.com/jasperf/50de85291e8873d651c3 . Normally BackupBuddy clones and adjusts all well included serialized data. I did see � where ' was supposed to be. Could that be the issue?

**Comment by jasperf** [comment]
Did replace the odd character by `'` but when I deactivated and activated the plugin I got `Plugin could not be activated because it triggered a fatal error.`

**Comment by jasperf** [comment]
Tried replacing the urls only and deactivating and activating. But no joy

**Comment by jasperf** [comment]
Fixing with https://github.com/Blogestudio/Fix-Serialization did not help and still get that same fatal error.

**Comment by jasperf** [comment]
Have the original cforms data here https://gist.github.com/jasperf/b58d41ad16fb7d0f0746 now. Will see if I can fix it to work on the staging site. Mayor pain this has become..

**Comment by bgermann** [comment]
Hi. Is the data corrupted only on the .dev or also on the .com site? Did you try cforms' export on .com and import on .dev?

**Comment by jasperf** [comment]
Only corrupted on .dev. Not sure if my version has an export option. How would I go about exporting form data?

**Comment by bgermann** [comment]
You can export via global settings -> top cforms Admin menu -> Backup & Restore All Settings

**Comment by jasperf** [comment]
In version v13.1I only see
![screen shot 2015-07-14 at 5 58 37 am](https://cloud.githubusercontent.com/assets/344138/8665514/6739c14a-29ed-11e5-993b-ca0e2b57092a.png)

**Comment by jasperf** [comment]
Seems the site is still running the original version and an outdated one. Read your readme better and saw:
>If you want to upgrade from the original cformsII from deliciousdays.com, please
upgrade to [version 14.6.0.5](https://plugins.svn.wordpress.org/cforms2/assets/cforms2.14.6.0.5.zip)
first, make sure you upgraded your settings (resave your global settings and every form)
and [backup your database](https://codex.wordpress.org/Backing_Up_Your_Database).
Then deactivate the original plugin and install the current version of this fork.

**Comment by bgermann** [comment]
So please follow this guide. I won't support old versions. If you experience the issue after upgrading to version 14.9.9 (then cloning the resulting database), you can open a new ticket.
